Repository ladybug-tools/honeybee-openstudio-gem, pull requests merged in 2020-07, with the labels that each got.

#127 ci(actions): send repo dispatch event too lbt-grasshopper on release
  .github/workflows/emit-release-event.yaml
Labels: enhancement

#128 fix(gemfile): Update version of gem in URBANopt Gemfile
  lib/files/urbanopt_Gemfile
Labels: bug

#129 fix(construction): Fix bug in creation of ShadingControl
  lib/from_honeybee/construction/windowshade.rb
  spec/tests/honeybee_construction_spec.rb
Labels: bug

#130 feat(ventcool): Add the ability to parse simple window-based ventilation
  lib/from_honeybee/_defaults/model.json
  lib/from_honeybee/_defaults/simulation-parameter.json
  lib/from_honeybee/geometry/room.rb
  lib/from_honeybee/ventcool/opening.rb
  spec/samples/model/model_complete_holes.json
  spec/samples/model/model_energy_window_ventilation.json
  spec/samples/model_large/lab_building.json
  spec/samples/model_large/single_family_home.json
  spec/samples/ventcool/ventilation_control_detailed.json
  spec/samples/ventcool/ventilation_control_simple.json
  spec/samples/ventcool/ventilation_opening_default.json
  spec/tests/honeybee_model_spec.rb
  spec/tests/honeybee_ventcool_spec.rb
Labels: enhancement, new development
