Repository ladybug-tools/honeybee-openstudio-gem, pull requests merged in 2020-11, with the labels that each got.

#147 fix(room): Handle the case of no program assigned to a room
  lib/from_honeybee/geometry/room.rb
Labels: bug

#149 feat(refactor): Release refactored version with OSM import capability
  lib/measures/from_honeybee_model/measure.rb
  lib/measures/from_honeybee_simulation_parameter/measure.rb
  lib/to_openstudio/schedule/ruleset.rb
Labels: bug, enhancement, new development

#150 fix(hvac): Fix issue with DOAS HVAC templates
  lib/to_openstudio/hvac/Model.hvac.rb
Labels: bug

#154 fix(hvac): Fix typo in HVAC template name
  lib/to_openstudio/hvac/Model.hvac.rb
Labels: bug

#155 Only load openstudio-standards when needed
  lib/to_openstudio/hvac/template.rb
Labels: enhancement
